- name: Run Database
  docker_container:
    name: db
    image: judodo/db
    state: started
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: backend