version: '3.3'
services:
  backend:
    container_name: backend
    build: ./simple-api-main
    networks:
      - backend
      - frontend
    depends_on:
      - db

  db:
    container_name: db
    build: ./DB
    networks:
      - backend
    volumes: 
      - /tmp/data:/var/lib/postgresql/data

  httpd:
    container_name: httpd
    build: ./httpd
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      - backend

networks:
  backend:
  frontend: